vlib work
vlib activehdl

vlib activehdl/xil_defaultlib
vlib activehdl/xpm
vlib activehdl/axi_infrastructure_v1_1_0
vlib activehdl/smartconnect_v1_0
vlib activehdl/axi_protocol_checker_v2_0_1
vlib activehdl/axi_vip_v1_1_1
vlib activehdl/processing_system7_vip_v1_0_3
vlib activehdl/lib_cdc_v1_0_2
vlib activehdl/lib_pkg_v1_0_2
vlib activehdl/fifo_generator_v13_2_1
vlib activehdl/lib_fifo_v1_0_10
vlib activehdl/blk_mem_gen_v8_4_1
vlib activehdl/lib_bmg_v1_0_10
vlib activehdl/lib_srl_fifo_v1_0_2
vlib activehdl/axi_datamover_v5_1_17
vlib activehdl/axi_vdma_v6_3_3
vlib activehdl/proc_sys_reset_v5_0_12
vlib activehdl/axis_infrastructure_v1_1_0
vlib activehdl/axis_data_fifo_v1_1_16
vlib activehdl/generic_baseblocks_v2_1_0
vlib activehdl/axi_register_slice_v2_1_15
vlib activehdl/axi_data_fifo_v2_1_14
vlib activehdl/axi_crossbar_v2_1_16
vlib activehdl/xlconcat_v2_1_1
vlib activehdl/axi_lite_ipif_v3_0_4
vlib activehdl/interrupt_control_v3_1_4
vlib activehdl/axi_iic_v2_0_18
vlib activehdl/xlconstant_v1_1_3
vlib activehdl/axi_mmu_v2_1_13
vlib activehdl/axi_protocol_converter_v2_1_15

vmap xil_defaultlib activehdl/xil_defaultlib
vmap xpm activehdl/xpm
vmap axi_infrastructure_v1_1_0 activehdl/axi_infrastructure_v1_1_0
vmap smartconnect_v1_0 activehdl/smartconnect_v1_0
vmap axi_protocol_checker_v2_0_1 activehdl/axi_protocol_checker_v2_0_1
vmap axi_vip_v1_1_1 activehdl/axi_vip_v1_1_1
vmap processing_system7_vip_v1_0_3 activehdl/processing_system7_vip_v1_0_3
vmap lib_cdc_v1_0_2 activehdl/lib_cdc_v1_0_2
vmap lib_pkg_v1_0_2 activehdl/lib_pkg_v1_0_2
vmap fifo_generator_v13_2_1 activehdl/fifo_generator_v13_2_1
vmap lib_fifo_v1_0_10 activehdl/lib_fifo_v1_0_10
vmap blk_mem_gen_v8_4_1 activehdl/blk_mem_gen_v8_4_1
vmap lib_bmg_v1_0_10 activehdl/lib_bmg_v1_0_10
vmap lib_srl_fifo_v1_0_2 activehdl/lib_srl_fifo_v1_0_2
vmap axi_datamover_v5_1_17 activehdl/axi_datamover_v5_1_17
vmap axi_vdma_v6_3_3 activehdl/axi_vdma_v6_3_3
vmap proc_sys_reset_v5_0_12 activehdl/proc_sys_reset_v5_0_12
vmap axis_infrastructure_v1_1_0 activehdl/axis_infrastructure_v1_1_0
vmap axis_data_fifo_v1_1_16 activehdl/axis_data_fifo_v1_1_16
vmap generic_baseblocks_v2_1_0 activehdl/generic_baseblocks_v2_1_0
vmap axi_register_slice_v2_1_15 activehdl/axi_register_slice_v2_1_15
vmap axi_data_fifo_v2_1_14 activehdl/axi_data_fifo_v2_1_14
vmap axi_crossbar_v2_1_16 activehdl/axi_crossbar_v2_1_16
vmap xlconcat_v2_1_1 activehdl/xlconcat_v2_1_1
vmap axi_lite_ipif_v3_0_4 activehdl/axi_lite_ipif_v3_0_4
vmap interrupt_control_v3_1_4 activehdl/interrupt_control_v3_1_4
vmap axi_iic_v2_0_18 activehdl/axi_iic_v2_0_18
vmap xlconstant_v1_1_3 activehdl/xlconstant_v1_1_3
vmap axi_mmu_v2_1_13 activehdl/axi_mmu_v2_1_13
vmap axi_protocol_converter_v2_1_15 activehdl/axi_protocol_converter_v2_1_15

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"/home/catabit/.opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/home/catabit/.opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/home/catabit/.opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93 \
"/home/catabit/.opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v2_0_1  -sv2k12 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/3b24/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \

vlog -work axi_vip_v1_1_1  -sv2k12 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/a16a/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_3  -sv2k12 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \

vcom -work lib_cdc_v1_0_2 -93 \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work lib_pkg_v1_0_2 -93 \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \

vlog -work fifo_generator_v13_2_1  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/5c35/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_1 -93 \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_1  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.v" \

vcom -work lib_fifo_v1_0_10 -93 \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f10a/hdl/lib_fifo_v1_0_rfs.vhd" \

vlog -work blk_mem_gen_v8_4_1  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \

vcom -work lib_bmg_v1_0_10 -93 \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/9340/hdl/lib_bmg_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_2 -93 \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_17 -93 \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/71f3/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vlog -work axi_vdma_v6_3_3  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl/axi_vdma_v6_3_rfs.v" \

vcom -work axi_vdma_v6_3_3 -93 \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl/axi_vdma_v6_3_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_axi_vdma_0_0/sim/design_1_axi_vdma_0_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
"../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \

vcom -work proc_sys_reset_v5_0_12 -93 \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_rst_ps7_0_50M_1/sim/design_1_rst_ps7_0_50M_1.vhd" \
"../../../bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/sim/ila_sfen_rxclk.vhd" \
"../../../bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/sim/ila_scnn_refclk.vhd" \
"../../../bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/sim/ila_sfen_refclk.vhd" \
"../../../bd/design_1/ipshared/f21f/hdl/SyncAsync.vhd" \
"../../../bd/design_1/ipshared/f21f/hdl/DPHY_Pkg.vhd" \
"../../../bd/design_1/ipshared/f21f/hdl/SyncAsyncReset.vhd" \
"../../../bd/design_1/ipshared/f21f/hdl/DebugLib.vhd" \
"../../../bd/design_1/ipshared/f21f/hdl/HS_Deserializer.vhd" \
"../../../bd/design_1/ipshared/f21f/hdl/GlitchFilter.vhd" \
"../../../bd/design_1/ipshared/f21f/hdl/HS_Clocking.vhd" \
"../../../bd/design_1/ipshared/f21f/hdl/InputBuffer.vhd" \
"../../../bd/design_1/ipshared/f21f/hdl/DPHY_LaneSFEN.vhd" \
"../../../bd/design_1/ipshared/f21f/hdl/DPHY_LaneSCNN.vhd" \
"../../../bd/design_1/ipshared/f21f/hdl/S_AXI_Lite.vhd" \
"../../../bd/design_1/ipshared/f21f/hdl/MIPI_DPHY_Receiver.vhd" \
"../../../bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/sim/design_1_MIPI_D_PHY_RX_0_0.vhd" \

vlog -work axis_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl/axis_infrastructure_v1_1_vl_rfs.v" \

vlog -work axis_data_fifo_v1_1_16  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl/axis_data_fifo_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/sim/line_buffer.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/sim/ila_rxclk_lane.vhd" \
"../../../bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/sim/ila_rxclk.vhd" \
"../../../bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/sim/ila_vidclk.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/sim/cdc_fifo.v" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ipshared/e363/hdl/SimpleFIFO.vhd" \
"../../../bd/design_1/ipshared/e363/hdl/CRC16_behavioral.vhd" \
"../../../bd/design_1/ipshared/e363/hdl/ECC.vhd" \
"../../../bd/design_1/ipshared/e363/hdl/DebugLib.vhd" \
"../../../bd/design_1/ipshared/e363/hdl/LM.vhd" \
"../../../bd/design_1/ipshared/e363/hdl/LLP.vhd" \
"../../../bd/design_1/ipshared/e363/hdl/MIPI_CSI_2_RX_v1_0_S_AXI_LITE.vhd" \
"../../../bd/design_1/ipshared/e363/hdl/MIPI_CSI2_Rx.vhd" \
"../../../bd/design_1/ipshared/e363/hdl/MIPI_CSI2_RxTop.vhd" \
"../../../bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/sim/design_1_MIPI_CSI_2_RX_0_0.vhd" \
"../../../bd/design_1/ipshared/40b8/hdl/LineBuffer.vhd" \
"../../../bd/design_1/ipshared/40b8/hdl/AXI_BayerToRGB.vhd" \
"../../../bd/design_1/ip/design_1_AXI_BayerToRGB_0_0/sim/design_1_AXI_BayerToRGB_0_0.vhd" \

vlog -work generic_baseblocks_v2_1_0  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_15  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/3ed1/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_14  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/9909/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_16  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/c631/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_xbar_1/sim/design_1_xbar_1.v" \
"../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
"../../../bd/design_1/sim/design_1.v" \

vlog -work xlconcat_v2_1_1  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_xlconcat_0_0/sim/design_1_xlconcat_0_0.v" \

vcom -work axi_lite_ipif_v3_0_4 -93 \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work interrupt_control_v3_1_4 -93 \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \

vcom -work axi_iic_v2_0_18 -93 \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4185/hdl/axi_iic_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../bd/design_1/ip/design_1_axi_iic_0_0/sim/design_1_axi_iic_0_0.vhd" \
"../../../bd/design_1/ipshared/c740/hdl/MotionController_v1_0_S00_AXI.vhd" \
"../../../bd/design_1/ipshared/c740/hdl/PWM_Driver.vhd" \
"../../../bd/design_1/ipshared/c740/hdl/MotionController_v1_0.vhd" \
"../../../bd/design_1/ip/design_1_MotionController_0_0/sim/design_1_MotionController_0_0.vhd" \
"../../../bd/design_1/ipshared/e906/hdl/sonarDriver_v1_0_S00_AXI.vhd" \
"../../../bd/design_1/ipshared/e906/hdl/sonarDriver_v1_0.vhd" \
"../../../bd/design_1/ip/design_1_sonarDriver_0_0/sim/design_1_sonarDriver_0_0.vhd" \

vlog -work xlconstant_v1_1_3  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_xlconstant_0_0/sim/design_1_xlconstant_0_0.v" \

vlog -work axi_mmu_v2_1_13  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/07ec/hdl/axi_mmu_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_s00_mmu_0/sim/design_1_s00_mmu_0.v" \

vlog -work axi_protocol_converter_v2_1_15  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ff69/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+/home/catabit/.opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
"../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

