#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun May 05 13:59:12 EEST 2019
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_1 axi_vip_v1_1_1 processing_system7_vip_v1_0_3 lib_cdc_v1_0_2 lib_pkg_v1_0_2 fifo_generator_v13_2_1 lib_fifo_v1_0_10 blk_mem_gen_v8_4_1 lib_bmg_v1_0_10 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_17 axi_vdma_v6_3_3 proc_sys_reset_v5_0_12 axis_infrastructure_v1_1_0 axis_data_fifo_v1_1_16 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_15 axi_data_fifo_v2_1_14 axi_crossbar_v2_1_16 xlconcat_v2_1_1 axis_broadcaster_v1_1_15 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_17 xlconstant_v1_1_3 xbip_utils_v3_0_8 axi_utils_v2_0_4 xbip_pipe_v3_0_4 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_4 xbip_dsp48_multadd_v3_0_4 xbip_bram18k_v3_0_4 mult_gen_v12_0_13 floating_point_v7_1_5 axi_protocol_converter_v2_1_15)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2017.4 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/3b24/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/a16a/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/5c35/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_1 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_10 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f10a/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_10 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/9340/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_17 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/71f3/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_3 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_vdma_0_0/sim/design_1_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps7_0_50M_1/sim/design_1_rst_ps7_0_50M_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/sim/ila_sfen_rxclk.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/sim/ila_scnn_refclk.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/sim/ila_sfen_refclk.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f21f/hdl/SyncAsync.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f21f/hdl/DPHY_Pkg.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f21f/hdl/SyncAsyncReset.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f21f/hdl/DebugLib.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f21f/hdl/HS_Deserializer.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f21f/hdl/GlitchFilter.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f21f/hdl/HS_Clocking.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f21f/hdl/InputBuffer.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f21f/hdl/DPHY_LaneSFEN.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f21f/hdl/DPHY_LaneSCNN.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f21f/hdl/S_AXI_Lite.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f21f/hdl/MIPI_DPHY_Receiver.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/sim/design_1_MIPI_D_PHY_RX_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v1_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl/axis_data_fifo_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/sim/line_buffer.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/sim/ila_rxclk_lane.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/sim/ila_rxclk.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/sim/ila_vidclk.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/sim/cdc_fifo.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/e363/hdl/SimpleFIFO.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/e363/hdl/CRC16_behavioral.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/e363/hdl/ECC.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/e363/hdl/DebugLib.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/e363/hdl/LM.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/e363/hdl/LLP.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/e363/hdl/MIPI_CSI_2_RX_v1_0_S_AXI_LITE.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/e363/hdl/MIPI_CSI2_Rx.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/e363/hdl/MIPI_CSI2_RxTop.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/sim/design_1_MIPI_CSI_2_RX_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/a13b/hdl/LineBuffer.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/a13b/hdl/AXI_BayerToRGB.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_AXI_BayerToRGB_0_0/sim/design_1_AXI_BayerToRGB_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/3ed1/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/9909/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/c631/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_1/sim/design_1_xbar_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconcat_0_0/sim/design_1_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/c740/hdl/MotionController_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/c740/hdl/PWM_Driver.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/c740/hdl/MotionController_v1_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_MotionController_0_0/sim/design_1_MotionController_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/e906/hdl/sonarDriver_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/e906/hdl/sonarDriver_v1_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_sonarDriver_0_0/sim/design_1_sonarDriver_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_broadcaster_0_0/hdl/tdata_design_1_axis_broadcaster_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_broadcaster_0_0/hdl/tuser_design_1_axis_broadcaster_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_broadcaster_v1_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/7cd3/hdl/axis_broadcaster_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_broadcaster_0_0/hdl/top_design_1_axis_broadcaster_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axis_broadcaster_0_0/sim/design_1_axis_broadcaster_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_vdma_0_1/sim/design_1_axi_vdma_0_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_proc_sys_reset_0_0/sim/design_1_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_proc_sys_reset_1_0/sim/design_1_proc_sys_reset_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_17 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/c450/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_0/sim/design_1_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_gpio_0_1/sim/design_1_axi_gpio_0_1.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/96d0/hdl/pwmRgbLed_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/96d0/hdl/pwmRgbLed_v1_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_pwmDriverAXI_0_0/sim/design_1_pwmDriverAXI_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_0/sim/design_1_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_8 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4173/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_4 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4575/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ee5e/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/da55/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/7b8d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/65ba/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/9eb4/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_13 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/257f/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_1_5 $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/b20f/hdl/floating_point_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/start_for_Sobel_1pcA.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/start_for_ZeroPadrcU.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/Sobel_1280u_720u_fYi.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/canny_edge_detecthbi.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/start_for_GrayArrudo.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/start_for_HystThrsc4.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/canny_edge_detectdEe.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/fifo_w8_d1_A.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/NonMaxSuppression.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/NonMaxSuppressionmb6.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/GrayArray2AXIS.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/AXIS2GrayArray.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/canny_edge_detectcud.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/fifo_w2_d1_A.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/canny_edge_detectibs.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/ZeroPadding.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/GaussianBlur.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/GaussianBlur_lineeOg.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/canny_edge_detectkbM.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/canny_edge_detectjbC.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/Sobel_1280u_720u_s.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/canny_edge_detectbkb.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/start_for_HystThrtde.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/HystThreshold.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/start_for_Gaussiaocq.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/start_for_NonMaxSqcK.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/HystThresholdComp.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/canny_edge_detection.v" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/verilog/canny_edge_detectg8j.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/ip/canny_edge_detection_ap_sitofp_4_no_dsp_32.vhd" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/d69f/hdl/ip/canny_edge_detection_ap_fsqrt_10_no_dsp_32.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_canny_edge_detection_0_1/sim/design_1_canny_edge_detection_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ff69/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/f8d8/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/4868" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ip/design_1_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" +incdir+"$ref_dir/../../../../SDCarVivado.srcs/sources_1/bd/design_1/ipshared/0ab1/hdl" +incdir+"/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
    "$ref_dir/../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/catabit/Zybo/SDCar/SDCarVivado/SDCarVivado.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
